[features]
seeds = false
[programs.localnet]
solana_twitter = "HRXo48WtYjQjoGnNF7tbSsMtPVHqCzkLoBV6AoysG14V"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jamesw/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
